import {render} from '@testing-library/react'
import HomePage from '../index'

test('result section start with 0', () => {
  const {getByTestId} = render(<HomePage />)
  const resultSection = getByTestId('result')
  expect(resultSection).toHaveTextContent(/^0$/)
})
test('press button 1, then display 1 in the result section', () => {
  const {getByText, getByTestId} = render(<HomePage />)
  const buttonOne = getByText('1', {selector: 'button'})
  buttonOne.click()
  const resultSection = getByTestId('result')
  expect(resultSection).toHaveTextContent(/^1$/)
})
test('press button 2, then display 2 in the result section', () => {
  const {getByText, getByTestId} = render(<HomePage />)
  const buttonOne = getByText('2', {selector: 'button'})
  buttonOne.click()
  const resultSection = getByTestId('result')
  expect(resultSection).toHaveTextContent(/^2$/)
})
test('press button 1 then 2, then display 12 in the result section', () => {
  const {getByText, getByTestId} = render(<HomePage />)
  const buttonOne = getByText('1', {selector: 'button'})
  buttonOne.click()
  const buttonTwo = getByText('2', {selector: 'button'})
  buttonTwo.click()
  const resultSection = getByTestId('result')
  expect(resultSection).toHaveTextContent(/^12$/)
})
test('press button 1 then 2, then press `+` button 3 display 3 in the result section', () => {
  const {getByText, getByTestId} = render(<HomePage />)
  const buttonOne = getByText('1', {selector: 'button'})
  buttonOne.click()
  const buttonTwo = getByText('2', {selector: 'button'})
  buttonTwo.click()
  const buttonPlus = getByText('+', {selector: 'button'})
  buttonPlus.click()
  const buttonThree = getByText('3', {selector: 'button'})
  buttonThree.click()
  const resultSection = getByTestId('result')
  expect(resultSection).toHaveTextContent(/^3$/)
})

test('press button 1 then 2, then press `+` button 3 then press `=`, should display 15 in the result section', () => {
  const {getByText, getByTestId} = render(<HomePage />)
  const buttonOne = getByText('1', {selector: 'button'})
  buttonOne.click()
  const buttonTwo = getByText('2', {selector: 'button'})
  buttonTwo.click()
  const buttonPlus = getByText('+', {selector: 'button'})
  buttonPlus.click()
  const buttonThree = getByText('3', {selector: 'button'})
  buttonThree.click()
  const buttonEqual = getByText('=', {selector: 'button'})
  buttonEqual.click()
  const resultSection = getByTestId('result')
  expect(resultSection).toHaveTextContent(/^15$/)
})
